#remote_theme: wowthemesnet/jekyll-theme-memoirs

# Website Info

name: "Maxel's Pages"
title: "Maxel's Pages"
description: "Code & write what we want."
logo: 'r/maxel.jpg'
favicon: 'favicon.ico'
baseurl: /
permalink: /:year/:month/:title/
email: maxelblack@outlook.com

# Configure

markdown: kramdown

jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

include: ["_pages"]
exclude: [README.md, Gemfile, Gemfile.lock]

# Authers

authors:
  maxelbk:
    name: "Maxel Black"
    display_name: "Maxel Black"
    avatar: 'r/maxel.jpg'
    email: maxelblack@outlook.com
    twitter: https://twitter.com/maxelbk
    description: "A simple student who loves coding."

# Other Things

# Adsense (change to "enabled" to activate, also your client id and ad slot.)
# Create a new ad unit from your Adsense account to get the slot.
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"
