# Website Info
title: "Maxel's Pages"
description: "Code & write what we want."
image: r/maxel.jpg

# Configure
remote_theme: wowthemesnet/jekyll-theme-memoirs

# Adsense (change to "enabled" to activate, also your client id and ad slot.)
# Create a new ad unit from your Adsense account to get the slot.
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"
